//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalCare.WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DentalCareEntities : DbContext
    {
        public DentalCareEntities()
            : base("name=DentalCareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dentalPiece> dentalPieces { get; set; }
        public virtual DbSet<implement_treatment> implement_treatment { get; set; }
        public virtual DbSet<implement> implements { get; set; }
        public virtual DbSet<person> persons { get; set; }
        public virtual DbSet<reservation> reservations { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<treatment> treatments { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
