//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalCare.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class implement_treatment
    {
        public int id { get; set; }
        public int idTreatment { get; set; }
        public int idImplement { get; set; }
    
        public virtual implement implement { internal get; set; }
        public virtual treatment treatment { internal get; set; }
    }
}
