//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalCare.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int id { get; set; }
        public System.DateTime reservation_date { get; set; }
        public string estatus { get; set; }
        public Nullable<int> idDentalPiece { get; set; }
        public Nullable<int> idDentist { get; set; }
        public Nullable<int> idPacient { get; set; }
        public Nullable<int> idTreatment { get; set; }
        public string observation { get; set; }
    
        public virtual dentalPiece dentalPiece { internal get; set; }
        public virtual person person { internal get; set; }
        public virtual person person1 { internal get; set; }
        public virtual treatment treatment { internal get; set; }
    }
}
